# PyTorch Tensor Manipulations

In [ ]:
import torch        # PyTorch 불러오기

## Tensor Shaping

### reshape: Change Tensor Shape

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x.size())     # 텐서 크기

torch.Size([3, 2, 2])


In [ ]:
print(x.reshape(12)) # 12 = 3 * 2 * 2       # 1차원으로 변환
print(x.reshape(-1))        # 자동 계산

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [ ]:
print(x.reshape(3, 4)) # 3 * 4 = 3 * 2 * 2      # 2차원 변환
print(x.reshape(3, -1))# 자동 계산

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
print(x.reshape(3, 1, 4))# 차원 확장
print(x.reshape(-1, 1, 4))# 자동 계산

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [ ]:
print(x.reshape(3, 2, 2, 1))# 4차원 변환

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


You can use 'view()' instead of 'reshape()' in some cases.

- https://pytorch.org/docs/stable/tensor_view.html
- https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view

### squeeze: Remove dimension which has only one element.

In [7]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())

torch.Size([1, 2, 2])


Remove any dimension which has only one element.

In [ ]:
print(x.squeeze())# 크기 1인 차원 제거
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


Remove certain dimension, if it has only one element.
If it is not, there would be no change.

In [ ]:
print(x.squeeze(0).size())# 특정 차원 제거
print(x.squeeze(1).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])


### unsqueeze: Insert dimension at certain index.

In [10]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(x.size())

torch.Size([2, 2])


In [ ]:
print(x.unsqueeze(2))# 차원 추가
print(x.unsqueeze(-1))# 마지막에 추가
print(x.reshape(2, 2, -1)) # reshape 활용

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
