# PyTorch Tensor

In [ ]:
import torch # PyTorch 불러오기

## Tensor Allocation

In [ ]:
ft = torch.FloatTensor([[1, 2],     # float 타입 텐서 생성
                        [3, 4]])
ft      # 텐서 출력

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
lt = torch.LongTensor([[1, 2],      # long(int64) 타입 텐서 생성
                       [3, 4]])
lt      # 텐서 출력

tensor([[1, 2],
        [3, 4]])

In [ ]:
bt = torch.ByteTensor([[1, 0],      # byte(bool처럼 사용) 텐서 생성
                       [0, 1]])
bt      # 텐서 출력

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [ ]:
x = torch.FloatTensor(3, 2)     # 3x2 크기의 랜덤 초기화 텐서 생성
x       # 텐서 출력

tensor([[0.0000e+00, 4.6566e-10],
        [0.0000e+00, 4.6566e-10],
        [9.8091e-45, 0.0000e+00]])

## NumPy Compatibility

In [ ]:
import numpy as np      # numpy 불러오기

# Define numpy array.
x = np.array([[1, 2],       # numpy 배열 생성
              [3, 4]])
print(x, type(x))      # 값과 타입 출력

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
x = torch.from_numpy(x)     # numpy → torch 변환
print(x, type(x))       # 변환 결과 확인

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [ ]:
x = x.numpy()       # torch → numpy 변환
print(x, type(x))       # 변환 결과 확인

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting

In [ ]:
ft.long()       # float → long 타입 변환

tensor([[1, 2],
        [3, 4]])

In [ ]:
lt.float()      # long → float 타입 변환

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
torch.FloatTensor([1, 0]).byte()        # float → byte 변환

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [ ]:
x = torch.FloatTensor([[[1, 2],     # 3차원 텐서 생성
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

Get tensor shape.

In [ ]:
print(x.size())     # 텐서 크기 출력
print(x.shape)      # 텐서 shape 출력

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


Get number of dimensions in the tensor.

In [ ]:
print(x.dim())      # 차원 수 출력
print(len(x.size()))        # 차원 수 동일하게 확인

3
3


Get number of elements in certain dimension of the tensor.

In [ ]:
print(x.size(1))        # 1번 축 크기
print(x.shape[1])       # 동일한 의미

2
2


Get number of elements in the last dimension.

In [ ]:
print(x.size(-1))       # 마지막 축 크기
print(x.shape[-1])      # 동일

2
2
