# PyTorch Tensor Operations

In [ ]:
import torch  # PyTorch 불러오기

## Arithmetic Element-wise Operations

In [ ]:
a = torch.FloatTensor([[1, 2],      # 텐서 a 생성
                       [3, 4]])
b = torch.FloatTensor([[2, 2],      # 텐서 b 생성
                       [3, 3]])

In [ ]:
a + b       # 덧셈

tensor([[3., 4.],
        [6., 7.]])

In [ ]:
a - b       # 뺄셈

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [ ]:
a * b       # 원소별 곱셈

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [ ]:
a / b       # 나눗셈

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [ ]:
a == b      # 비교 (같은지)


tensor([[False,  True],
        [ True, False]])

In [ ]:
a != b      # 비교 (다른지)

tensor([[ True, False],
        [False,  True]])

In [ ]:
a ** b      # 거듭제곱

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

In [ ]:
print(a)        # 원본 출력
print(a.mul(b))     # 곱셈 (새 텐서 반환)
print(a)        # 원본 유지
print(a.mul_(b))         # in-place 곱셈 (a 변경)
print(a)         # 변경된 값 출력

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [ ]:
x = torch.FloatTensor([[1, 2],      # 텐서 생성
                       [3, 4]])

In [ ]:
print(x.sum())      # 전체 합
print(x.mean())      # 평균

tensor(10.)
tensor(2.5000)


In [ ]:
print(x.sum(dim=0))      # 열 기준 합
print(x.sum(dim=-1))    # 행 기준 합

tensor([4., 6.])
tensor([3., 7.])


## Broadcast in Operations

What we did before,

In [ ]:
x = torch.FloatTensor([[1, 2]])     # 1x2 텐서
y = torch.FloatTensor([[4, 8]])      # 1x2 텐서

print(x.size())     # 크기 출력
print(y.size())     # 크기 출력

torch.Size([1, 2])
torch.Size([1, 2])


In [ ]:
z = x + y       # 같은 shape 연산
print(z)        #원본 출력
print(z.size())     # 크기 출력

tensor([[ 5., 10.]])
torch.Size([1, 2])


Broadcast feature provides operations between different shape of tensors.

### Tensor + Scalar

In [ ]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1       # 스칼라

print(x.size())

torch.Size([2, 2])


In [ ]:
z = x + y       # broadcasting
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### Tensor + Vector

In [ ]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,       # 1차원 텐서
                       5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [ ]:
z = x + y       # broadcasting
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [ ]:
x = torch.FloatTensor([[[1, 2]]])       # 3D 텐서
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [ ]:
z = x + y       # broadcasting
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [22]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [ ]:
z = x + y       # broadcasting
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


Note that you need to be careful before using broadcast feature.

### Failure Case

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y       # broadcasting (불가능한 경우 에러 발생 가능)

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2