# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [2]:
# 목표 텐서 생성
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
# 초기 x를 target과 같은 크기의 랜덤 값으로 생성
x = torch.rand_like(target)
# gradient 추적 활성화
x.requires_grad = True

In [4]:
# MSE 손실 계산
loss = F.mse_loss(x, target)

In [5]:
# 학습 파라미터 설정
threshold = 1e-5
learning_rate = 1.0
iter_cnt = 0

# 손실이 threshold보다 클 동안 반복
while loss > threshold:
    iter_cnt += 1
    
    # gradient 계산
    loss.backward()
    
    # gradient descent 업데이트
    x = x - learning_rate * x.grad
    
    # gradient 추적을 위한 detach 및 requires_grad 재설정
    x.detach_()
    x.requires_grad_(True)
    
    # 새로운 loss 계산
    loss = F.mse_loss(x, target)
    
    # 진행 상황 출력
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 9.8213e-02
tensor([[0.4684, 0.7116, 0.2905],
        [0.5175, 0.4637, 0.2776],
        [0.8113, 0.7130, 0.3106]], requires_grad=True)
2-th Loss: 5.9413e-02
tensor([[0.3865, 0.5979, 0.2926],
        [0.4914, 0.4718, 0.3493],
        [0.7866, 0.7323, 0.4416]], requires_grad=True)
3-th Loss: 3.5941e-02
tensor([[0.3229, 0.5095, 0.2943],
        [0.4711, 0.4780, 0.4050],
        [0.7674, 0.7474, 0.5435]], requires_grad=True)
4-th Loss: 2.1742e-02
tensor([[0.2733, 0.4407, 0.2955],
        [0.4553, 0.4829, 0.4483],
        [0.7524, 0.7591, 0.6227]], requires_grad=True)
5-th Loss: 1.3153e-02
tensor([[0.2348, 0.3872, 0.2965],
        [0.4430, 0.4867, 0.4820],
        [0.7407, 0.7682, 0.6843]], requires_grad=True)
6-th Loss: 7.9565e-03
tensor([[0.2049, 0.3456, 0.2973],
        [0.4334, 0.4897, 0.5082],
        [0.7317, 0.7752, 0.7323]], requires_grad=True)
7-th Loss: 4.8132e-03
tensor([[0.1816, 0.3133, 0.2979],
        [0.4260, 0.4920, 0.5286],
        [0.7246, 0.7807, 0.7695]], requi